version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      # - MONGODB_URI=mongodb://mongo:27017/auth
      - MONGODB_URI=${MONGODB_URI}
      # - BLOCK_FROST_PROJECT_ID=${BLOCK_FROST_PROJECT_ID}
      # - GITHUB_SECRET=${GITHUB_SECRET}
      # - GITHUB_ID=${GITHUB_ID}
      # - AUTH_SECRET=${AUTH_SECRET}
    depends_on:
      - mongo
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
