import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Roboto } from "next/font/google";

import "./globals.css";

import ClientSessionProvider from "@/lib/client-session-provider";

const roboto = Roboto({
  weight: ["500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased ${roboto.className}`}>
        <ClientSessionProvider>
          <main className='flex items-center justify-center min-h-screen bg-gray-100'>{children}</main>
        </ClientSessionProvider>

        <Toaster position='bottom-right' />
      </body>
    </html>
  );
}
