import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Roboto } from "next/font/google";

import "./globals.css";

import ClientSessionProvider from "@/lib/client-session-provider";
import { cn } from "@/lib/utils";

const roboto = Roboto({
  weight: ["500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn("min-h-screen bg-background antialiased overscroll-none", roboto.variable)}>
        <ClientSessionProvider>{children}</ClientSessionProvider>

        <Toaster position='bottom-right' />
      </body>
    </html>
  );
}
